// src/auth/permissions.ts
export const PERMISSIONS = {
  SUBMIT_EXPENSE: "SUBMIT_EXPENSE",
  APPROVE_EXPENSE: "APPROVE_EXPENSE",
  VIEW_TEAM_EXPENSES: "VIEW_TEAM_EXPENSES",
  VIEW_ALL_EXPENSES: "VIEW_ALL_EXPENSES",
  EXPORT_REPORTS: "EXPORT_REPORTS",
  MANAGE_USERS: "MANAGE_USERS",
  MANAGE_CATEGORIES: "MANAGE_CATEGORIES",
  MANAGE_ROLES: "MANAGE_ROLES",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// Optional: group them for UI
export const PERMISSION_GROUPS = {
  EXPENSES: [
    PERMISSIONS.SUBMIT_EXPENSE,
    PERMISSIONS.APPROVE_EXPENSE,
    PERMISSIONS.VIEW_TEAM_EXPENSES,
    PERMISSIONS.VIEW_ALL_EXPENSES,
    PERMISSIONS.EXPORT_REPORTS,
  ],
  ADMIN: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_CATEGORIES,
    PERMISSIONS.MANAGE_ROLES,
  ],
};
